export enum ProductCategory {
  APPAREL_AND_ACCESSORIES = "APPAREL_AND_ACCESSORIES",
  STYLE_AND_FASHION = "STYLE_AND_FASHION",
  HOME_AND_GARDEN = "HOME_AND_GARDEN",
  SPORTING_GOODS = "SPORTING_GOODS",
  HEALTH_AND_WELLNESS = "HEALTH_AND_WELLNESS",
  MEDICAL_HEALTH = "MEDICAL_HEALTH",
  CHILDREN_AND_INFANTS = "CHILDREN_AND_INFANTS",
  PETS_AND_PET_SUPPLIES = "PETS_AND_PET_SUPPLIES",
  CONSUMER_ELECTRONIC_GOODS = "CONSUMER_ELECTRONIC_GOODS",
  HOME_IMPROVEMENT = "HOME_IMPROVEMENT",
  LEGAL_DRUGS = "LEGAL_DRUGS",
  FOOD_AND_BEVERAGE = "FOOD_AND_BEVERAGE"
}